### ISSUE TITLE
I annotated the command as mentioned above,

### ISSUE THREAD

**Issue by carlini** [carlini/audio_adversarial_examples#10]
but it gives me another error,
ValueError: Dimension must be 3 but is 4 for 'transpose' (op: 'Transpose') with input shapes: [?,?,?], [4].

Do you know how to solve it?
Thank you!

_Originally posted by @JiajieZhang-Georgia in https://github.com/carlini/audio_adversarial_examples/issues/7#issuecomment-429381750_

**Comment by carlini** [comment]
Could you copy a full trace so I can see where this error happens?

**Comment by JiajieZhang-Georgia** [comment]
Yes!



WARNING:tensorflow:From make_checkpoint.py:39: calling import_graph_def (from tensorflow.python.framework.importer) with op_dict is deprecated and will be removed in a future version.
Instructions for updating:
Please file an issue at https://github.com/tensorflow/tensorflow/issues if you depend on this feature.
Traceback (most recent call last):
  File "/home/georgia/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1626, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension must be 3 but is 4 for 'transpose' (op: 'Transpose') with input shapes: [?,?,?], [4].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "make_checkpoint.py", line 52, in <module>
    logits2 = DeepSpeech.BiRNN(new_input, [len(mfcc)], [0]*10)
  File "DeepSpeech/DeepSpeech.py", line 409, in BiRNN
    batch_x = tf.transpose(batch_x, [1, 0, 2, 3])
  File "/home/georgia/.local/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1419, in transpose
    ret = transpose_fn(a, perm, name=name)
  File "/home/georgia/.local/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 8741, in transpose
    "Transpose", x=x, perm=perm, name=name)
  File "/home/georgia/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/georgia/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/georgia/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
    op_def=op_def)
  File "/home/georgia/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1790, in __init__
    control_input_ops)
  File "/home/georgia/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1629, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension must be 3 but is 4 for 'transpose' (op: 'Transpose') with input shapes: [?,?,?], [4].

**Comment by carlini** [comment]
It looks like you didn't checkout tags/v0.1.1.

**Comment by JiajieZhang-Georgia** [comment]
Sorry about that,
maybe we should close the issue.

I checked the version, and got some memory problem, like 'std::bad_alloc',
since I just tried in my local environment,
later I can try it on server and see if it works,
thanks for your reply.
