### ISSUE TITLE
Failed to Classify the generated phrase

### ISSUE THREAD

**Issue by 040840308** [carlini/audio_adversarial_examples#15]
hi, everyone

     I install deepspeech-gpu through install deepspeech-gpu.
    When I tried to classify the generated phrase using the following command:
          deepspeech models/output_graph.pb adversarial.wav models/alphabet.txt.

    1) I found the required argument format is different ( not same as the above command), as follows:
        usage: deepspeech [-h] --model MODEL --alphabet ALPHABET [--lm [LM]]
                  [--trie [TRIE]] --audio AUDIO [--version]
       deepspeech: error: the following arguments are required: --model, --alphabet, --audio

   2) When I enter the command according to this format, how errors happened.
       (AdversarialAudio) root@zy-Lenovo:/home/zy/Adversarial_AudioXiaolei# deepspeech --model models/output_graph.pb --alphabet models/alphabet.txt --audio adversarial-00002-targeted.wav
Loading model from file models/output_graph.pb
TensorFlow: v1.11.0-9-g97d851f
DeepSpeech: v0.3.0-0-gef6b5bd
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
2018-11-15 21:32:06.537488: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2018-11-15 21:32:06.537521: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: zy-Lenovo
2018-11-15 21:32:06.537528: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: zy-Lenovo
2018-11-15 21:32:06.537548: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 375.26.0
2018-11-15 21:32:06.537716: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 375.26.0
2018-11-15 21:32:06.537725: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:305] kernel version seems to match DSO: 375.26.0
Not found: Op type not registered 'Assert' in binary running on zy-Lenovo. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
Traceback (most recent call last):
  File "/root/virtualenvs/AdversarialAudio/bin/deepspeech", line 11, in <module>
    sys.exit(main())
  File "/root/virtualenvs/AdversarialAudio/lib/python3.5/site-packages/deepspeech/client.py", line 81, in main
    ds = Model(args.model, N_FEATURES, N_CONTEXT, args.alphabet, BEAM_WIDTH)
  File "/root/virtualenvs/AdversarialAudio/lib/python3.5/site-packages/deepspeech/__init__.py", line 14, in __init__
    raise RuntimeError("CreateModel failed with error code {}".format(status))
RuntimeError: CreateModel failed with error code 5

        Thanks for any advice.

**Comment by carlini** [comment]
It looks like the deepseech program has been updated since last year and no longer works with that model file. I'll see if there's a way to get an older version.

**Comment by 040840308** [comment]
I think so, too.

**Comment by carlini** [comment]
I don't have a good solution here for how to get an old version of the utility. I'll remove this suggestion from the README.
