### ISSUE TITLE
Error about def ctc_label_dense_to_sparse(labels, label_lengths, batch_size) from Util.text

### ISSUE THREAD

**Issue by 040840308** [carlini/audio_adversarial_examples#20]
Hi, carlini

     I tried to run DeepSpeech-0.4.1 on tensorflow 1.12.0 with python3.5.  I want to extract the CTC logits from a a target phrase using the ctc_label_dense_to_sparse function. However, I encountered an error as follows:  Traceback (most recent call last):
     
     target = ctc_label_dense_to_sparse(target_phrase, target_phrase_lengths, 1)
File "DeepSpeech/util/text.py", line 191, in ctc_label_dense_to_sparse
dense_mask = tf.scan(range_less_than, label_lengths, initializer=init, parallel_iterations=1)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/functional_ops.py", line 684, in scan
maximum_iterations=n)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 3274, in while_loop
return_same_structure)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2994, in BuildLoop
pred, body, original_loop_vars, loop_vars, shape_invariants)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2966, in _BuildLoop
next_vars.append(_AddNextAndBackEdge(m, v))
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 667, in _AddNextAndBackEdge
_EnforceShapeInvariant(m, v)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 611, in _EnforceShapeInvariant
(input_t.name, input_t.shape, n_shape))
ValueError: Input tensor 'ExpandDims:0' enters the loop with shape (1, 42), but has shape (1, ?) after one iteration. To allow the shape to vary across iterations, use the shape_invariants argument of tf.while_loop to specify a less-specific shape.

Do you know why this happen? I run your same code.

Thanks

**Comment by carlini** [comment]
My code hooks into DeepSpeech in a contrived manner. It's probably not going to work with anything that's not the version specified in the README.
