### ISSUE TITLE
make_checkpoint.py  Dimension 0 in both shapes must be equal

### ISSUE THREAD

**Issue by nbufl** [carlini/audio_adversarial_examples#23]
I am trying to attack my own model that I trained with DS 0.1.1. I trained it with parameter n_hidden = 736

When I try to use make_checkpoint.py, I get this error

 python3 make_checkpoint.py
 python3 make_checkpoint.py
WARNING:tensorflow:From make_checkpoint.py:60: calling import_graph_def (from tensorflow.python.framework.importer) with op_dict is deprecated and will be removed in a future version.
Instructions for updating:
Please file an issue at https://github.com/tensorflow/tensorflow/issues if you depend on this feature.
Traceback (most recent call last):
  File "/home/xor/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1567, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 2048 and 736. Shapes are [2048] and [736]. for 'Assign' (op: 'Assign') with input shapes: [2048], [736].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "make_checkpoint.py", line 79, in <module>
    sess.run(var.assign(sess.run('newname/'+var.name)))
  File "/home/xor/.local/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 615, in assign
    return state_ops.assign(self._variable, value, use_locking=use_locking)
  File "/home/xor/.local/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 283, in assign
    validate_shape=validate_shape)
  File "/home/xor/.local/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 60, in assign
    use_locking=use_locking, name=name)
  File "/home/xor/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/xor/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/xor/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1734, in __init__
    control_input_ops)
  File "/home/xor/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1570, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 0 in both shapes must be equal, but are 2048 and 736. Shapes are [2048] and [736]. for 'Assign' (op: 'Assign') with input shapes: [2048], [736].

I tried a fresh install of DS 0.1.1 and a new virtualenv but I keep getting this error. What to do?

**Comment by nbufl** [comment]
I fixed this issue simply by changing the default value of n_hidden from 2048 to 736.
