### ISSUE TITLE
Error running make_checkpoint.py

### ISSUE THREAD

**Issue by tom-doerr** [carlini/audio_adversarial_examples#24]
When running `python3 make_checkpoint.py` I get  the error `ImportError: No module named 'xdg'`. 
After installing it with `pip3 install pyxdg` I get the following error when trying to execute `make_checkpoint.py`:

```
root@710e3f9a8769:/bachelorarbeit/robust_audio_ae# python3 make_checkpoint.py
Traceback (most recent call last):
  File "/root/.local/lib/python3.5/site-packages/absl/flags/_flag.py", line 181, in _parse
    return self.parser.parse(argument)
  File "/root/.local/lib/python3.5/site-packages/absl/flags/_argument_parser.py", line 114, in parse
    type(argument)))
TypeError: flag value must be a string, found "<class 'int'>"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "make_checkpoint.py", line 28, in <module>
    import DeepSpeech
  File "DeepSpeech/DeepSpeech.py", line 50, in <module>
    tf.app.flags.DEFINE_string  ('coord_retries',    100,         'number of tries of workers connecting to training coordinator before failing')
  File "/root/.local/lib/python3.5/site-packages/tensorflow/python/platform/flags.py", line 58, in wrapper
    return original_function(*args, **kwargs)
  File "/root/.local/lib/python3.5/site-packages/absl/flags/_defines.py", line 241, in DEFINE_string
    DEFINE(parser, name, default, help, flag_values, serializer, **args)
  File "/root/.local/lib/python3.5/site-packages/absl/flags/_defines.py", line 81, in DEFINE
    DEFINE_flag(_flag.Flag(parser, serializer, name, default, help, **args),
  File "/root/.local/lib/python3.5/site-packages/absl/flags/_flag.py", line 110, in __init__
    self._set_default(default)
  File "/root/.local/lib/python3.5/site-packages/absl/flags/_flag.py", line 211, in _set_default
    self.default = self._parse(value)
  File "/root/.local/lib/python3.5/site-packages/absl/flags/_flag.py", line 184, in _parse
    'flag --%s=%s: %s' % (self.name, argument, e))
absl.flags._exceptions.IllegalFlagValueError: flag --coord_retries=100: flag value must be a string, found "<class 'int'>"
```

I run it with different versions of python, deepspeech, tensorflow  and xdg. I also tried to run it in virtualenvs and docker, but I always get the same error message.
Any help is greatly appreciated!

**Comment by tom-doerr** [comment]
I solved it by changing the value 100 to '100' (string instead of int) in DeepSpeech/DeepSpeech.py.
